import os
from datetime import datetime

class ReportAgent:
    """
    Agent 5 — WRITER
    Generates a structured medical report locally.
    No API key needed — completely free!
    """

    def process(self, extracted: dict) -> dict:
        label      = extracted.get("label", "Unknown")
        confidence = extracted.get("confidence", 0.0)
        features   = extracted.get("features", {})
        image_path = extracted.get("image_path", "Unknown")
        now        = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        tumor_area   = features.get("tumor_area_pct", 0)
        circularity  = features.get("circularity", 0)
        mean_int     = features.get("mean_intensity", 0)
        centroid     = features.get("centroid", None)
        bbox         = features.get("bounding_box", None)

        # ── Severity assessment ────────────────────────────────────────────────
        if label == "No Tumor":
            severity    = "None"
            urgency     = "Routine follow-up recommended."
            finding_txt = "No abnormal mass or lesion detected in the brain MRI scan."
            interp_txt  = ("The automated analysis did not identify any tumor-like regions. "
                           "The scan appears within normal parameters based on the AI model's assessment.")
        else:
            if tumor_area < 5:
                severity = "Small"
            elif tumor_area < 15:
                severity = "Moderate"
            else:
                severity = "Large"

            urgency = "Immediate consultation with a neurologist is strongly advised."
            finding_txt = (f"A potential tumor region has been identified occupying approximately "
                           f"{tumor_area}% of the scan area.")
            interp_txt  = (f"The AI model detected a {severity.lower()} abnormal region with "
                           f"{confidence}% confidence. "
                           f"The region exhibits a circularity index of {circularity}, "
                           f"which may indicate {'a well-defined mass' if circularity > 0.6 else 'an irregular lesion'}. "
                           f"Mean pixel intensity within the region is {mean_int}.")

        # ── Centroid / bbox text ───────────────────────────────────────────────
        location_txt = "N/A"
        if centroid:
            location_txt = f"Centroid at pixel coordinates (x={centroid[0]}, y={centroid[1]})"
        if bbox:
            location_txt += f", Bounding box: {bbox}"

        # ── Build report ───────────────────────────────────────────────────────
        report = f"""
╔══════════════════════════════════════════════════════════════════╗
║           BRAIN MRI AUTOMATED ANALYSIS REPORT                   ║
╚══════════════════════════════════════════════════════════════════╝

Date & Time  : {now}
Image File   : {os.path.basename(image_path)}
Analyzed By  : Multi-Agent AI Pipeline (5 Agents)

──────────────────────────────────────────────────────────────────
1. PATIENT SCAN SUMMARY
──────────────────────────────────────────────────────────────────
  Scan Type        : Brain MRI
  Image File       : {os.path.basename(image_path)}
  Analysis Status  : Complete

──────────────────────────────────────────────────────────────────
2. FINDINGS
──────────────────────────────────────────────────────────────────
  Diagnosis        : {label}
  Confidence       : {confidence}%
  Severity         : {severity}
  Tumor Area       : {tumor_area}% of scan
  Location         : {location_txt}
  Circularity      : {circularity}
  Mean Intensity   : {mean_int}

  {finding_txt}

──────────────────────────────────────────────────────────────────
3. INTERPRETATION
──────────────────────────────────────────────────────────────────
  {interp_txt}

──────────────────────────────────────────────────────────────────
4. RECOMMENDATION
──────────────────────────────────────────────────────────────────
  {urgency}
  
  • Share this report with a licensed radiologist or neurologist.
  • Do not rely solely on this AI analysis for medical decisions.
  • Further imaging (CT/PET scan) may be required for confirmation.

══════════════════════════════════════════════════════════════════
⚠️  DISCLAIMER
This report is generated by an AI system for educational purposes
only. It is NOT a substitute for professional medical diagnosis.
Always consult a qualified medical professional for health decisions.
══════════════════════════════════════════════════════════════════
"""

        print(f"  ✅ ReportAgent: report generated locally ({len(report)} chars)")

        return {**extracted, "report": report}
